/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogodavelha;

import static com.mycompany.jogodavelha.Tela.aux.jogadorDois;
import static com.mycompany.jogodavelha.Tela.aux.jogadorUm;
import com.sun.tools.javac.Main;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Tela extends javax.swing.JFrame {

    private int contador = 0;
    private int placarX = 0;
    private int placarO = 0;
    private int placarvelha = 0;
    private int PlacarPartidas = 0;
    private int placarJogadas = 0;

    public Tela() {
        initComponents();

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        labelX = new javax.swing.JLabel();
        labelO = new javax.swing.JLabel();
        labelPlacar = new javax.swing.JLabel();
        labelJogadas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nome2 = new javax.swing.JLabel();
        SimboloX = new javax.swing.JLabel();
        SimboloO = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        qtdPartidas = new javax.swing.JLabel();
        qtdVelhas = new javax.swing.JLabel();
        velha = new javax.swing.JLabel();
        qtdpartidas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(500, 100));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao1.setBackground(new java.awt.Color(255, 204, 102));
        botao1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao1.setForeground(new java.awt.Color(0, 0, 0));
        botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1MouseClicked(evt);
            }
        });
        jPanel1.add(botao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 128, 124));

        botao2.setBackground(new java.awt.Color(255, 204, 102));
        botao2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao2.setForeground(new java.awt.Color(0, 0, 0));
        botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2MouseClicked(evt);
            }
        });
        jPanel1.add(botao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 1, 128, 124));

        botao3.setBackground(new java.awt.Color(255, 204, 102));
        botao3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao3.setForeground(new java.awt.Color(0, 0, 0));
        botao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao3MouseClicked(evt);
            }
        });
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });
        jPanel1.add(botao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 1, 128, 124));

        botao4.setBackground(new java.awt.Color(255, 204, 102));
        botao4.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao4.setForeground(new java.awt.Color(0, 0, 0));
        botao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao4MouseClicked(evt);
            }
        });
        jPanel1.add(botao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 125, 128, 124));

        botao5.setBackground(new java.awt.Color(255, 204, 102));
        botao5.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao5.setForeground(new java.awt.Color(0, 0, 0));
        botao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao5MouseClicked(evt);
            }
        });
        jPanel1.add(botao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 125, 128, 124));

        botao6.setBackground(new java.awt.Color(255, 204, 102));
        botao6.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao6.setForeground(new java.awt.Color(0, 0, 0));
        botao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao6MouseClicked(evt);
            }
        });
        jPanel1.add(botao6, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 125, 128, 124));

        botao7.setBackground(new java.awt.Color(255, 204, 102));
        botao7.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao7.setForeground(new java.awt.Color(0, 0, 0));
        botao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao7MouseClicked(evt);
            }
        });
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });
        jPanel1.add(botao7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 249, 128, 124));

        botao8.setBackground(new java.awt.Color(255, 204, 102));
        botao8.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao8.setForeground(new java.awt.Color(0, 0, 0));
        botao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao8MouseClicked(evt);
            }
        });
        jPanel1.add(botao8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 249, 128, 124));

        botao9.setBackground(new java.awt.Color(255, 204, 102));
        botao9.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botao9.setForeground(new java.awt.Color(0, 0, 0));
        botao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao9MouseClicked(evt);
            }
        });
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });
        jPanel1.add(botao9, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 249, 128, 124));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, 386, 374));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelX.setBackground(new java.awt.Color(0, 0, 0));
        labelX.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        labelX.setForeground(new java.awt.Color(0, 0, 0));
        labelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelX.setText("0");
        labelX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(labelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, 42, 49));

        labelO.setBackground(new java.awt.Color(0, 0, 0));
        labelO.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        labelO.setForeground(new java.awt.Color(0, 0, 0));
        labelO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelO.setText("0");
        labelO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.add(labelO, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 0, 42, 49));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 386, -1));

        labelPlacar.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        labelPlacar.setForeground(new java.awt.Color(0, 0, 0));
        labelPlacar.setText("Placar:");
        labelPlacar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(labelPlacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 7, -1, 66));

        labelJogadas.setBackground(new java.awt.Color(204, 204, 204));
        labelJogadas.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        labelJogadas.setForeground(new java.awt.Color(204, 204, 204));
        labelJogadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(labelJogadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 50, 50));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("QTD.JOGADAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 130, 40));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome2.setBackground(new java.awt.Color(0, 0, 0));
        nome2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        nome2.setForeground(new java.awt.Color(0, 0, 0));
        nome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 125, 40));

        SimboloX.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        SimboloX.setForeground(new java.awt.Color(0, 0, 0));
        SimboloX.setText("X");
        jPanel4.add(SimboloX, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 22, -1));

        SimboloO.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        SimboloO.setForeground(new java.awt.Color(0, 0, 0));
        SimboloO.setText("o");
        jPanel4.add(SimboloO, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 21, 22, -1));

        nome1.setBackground(new java.awt.Color(0, 0, 0));
        nome1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        nome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nome1KeyReleased(evt);
            }
        });
        jPanel4.add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 125, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 390, 60));

        qtdPartidas.setBackground(new java.awt.Color(204, 204, 204));
        qtdPartidas.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        qtdPartidas.setForeground(new java.awt.Color(204, 204, 204));
        qtdPartidas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(qtdPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 538, 43, 49));

        qtdVelhas.setBackground(new java.awt.Color(204, 204, 204));
        qtdVelhas.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        qtdVelhas.setForeground(new java.awt.Color(204, 204, 204));
        qtdVelhas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(qtdVelhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 423, 43, 48));

        velha.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        velha.setForeground(new java.awt.Color(204, 204, 204));
        velha.setText("QTD. VELHAS");
        getContentPane().add(velha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 36));

        qtdpartidas.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        qtdpartidas.setForeground(new java.awt.Color(204, 204, 204));
        qtdpartidas.setText("Qtd. partidas");
        getContentPane().add(qtdpartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 495, -1, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\img jogoVelha\\imagem fundo jogo velha.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 550, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao9ActionPerformed

    private void botao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao9MouseClicked
        gerencia(botao9);
    }//GEN-LAST:event_botao9MouseClicked

    private void botao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao8MouseClicked
        gerencia(botao8);
    }//GEN-LAST:event_botao8MouseClicked

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao7MouseClicked
        gerencia(botao7);
    }//GEN-LAST:event_botao7MouseClicked

    private void botao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao6MouseClicked
        gerencia(botao6);
    }//GEN-LAST:event_botao6MouseClicked

    private void botao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao5MouseClicked
        gerencia(botao5);
    }//GEN-LAST:event_botao5MouseClicked

    private void botao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao4MouseClicked
        gerencia(botao4);
    }//GEN-LAST:event_botao4MouseClicked

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed

    }//GEN-LAST:event_botao3ActionPerformed

    private void botao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao3MouseClicked
        gerencia(botao3);
    }//GEN-LAST:event_botao3MouseClicked

    private void botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseClicked
        gerencia(botao2);
    }//GEN-LAST:event_botao2MouseClicked

    private void botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseClicked
        gerencia(botao1);
        ;
    }//GEN-LAST:event_botao1MouseClicked

    private void nome1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome1KeyReleased
        // nome1.setText(nomeJogadorX);
    }//GEN-LAST:event_nome1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Tela().setVisible(true);
            }
        });
    }

    public void gerencia(JButton botao) {
        String text = botao.getText();
        if (text == "" && botao.isEnabled()) {
            if (aux.contador % 2 == 0) {
                botao.setText("X");
                placarJogadas++;
                labelJogadas.setText(placarJogadas + " ");
            } else {
                botao.setText("O");
                placarJogadas++;
                labelJogadas.setText(placarJogadas + " ");
                

            }
            aux.contador += 1;
            
            vencedor();
        }
    }

    public void nomesJogadores(String nomeJogadorX, String nomeJogadorO) {
        String jogador1 = nomeJogadorX;
        String jogador2 = nomeJogadorO;
        nome1.setVisible(true);
        nome2.setVisible(true);
        nome1.setText(jogadorDois);
        nome2.setText(jogadorUm);

        // aqui voce usa os nomes dos jogadores que vieram da outra tela para colocar os nomes nessa tela
    }

    class aux {

        static int mat[][] = new int[3][3];
        static int contador = 0;
        static String jogadorUm;
        static String jogadorDois;
    }

    public void vencedor() {
        String b1, b2, b3, b4, b5, b6, b7, b8, b9;

        b1 = botao1.getText();
        b2 = botao2.getText();
        b3 = botao3.getText();
        b4 = botao4.getText();
        b5 = botao5.getText();
        b6 = botao6.getText();
        b7 = botao7.getText();
        b8 = botao8.getText();
        b9 = botao9.getText();

        if (b1 != "" && b1 == b2 && b3 == b2) {
            reseta();
            String tipo;

            if (b1 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();

            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();

            }

        } else if (b4 != "" && b4 == b5 && b6 == b5) {

            if (b4 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b7 != "" && b7 == b8 && b9 == b8) {

            if (b7 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b1 != "" && b1 == b4 && b7 == b4) {

            if (b1 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b2 != "" && b2 == b5 && b8 == b5) {

            if (b8 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b3 != "" && b3 == b6 && b9 == b6) {

            if (b3 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b1 != "" && b1 == b5 && b9 == b5) {

            if (b1 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (b3 != "" && b3 == b5 && b7 == b5) {

            if (b5 == "X") {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorUm + " Ganhou por X");
                placarX++;
                labelX.setText(placarX + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            } else {

                JOptionPane.showMessageDialog(null, "jogador " + aux.jogadorDois + " Ganhou por O");
                placarO++;
                labelO.setText(placarO + " ");
                PlacarPartidas++;
                qtdPartidas.setText(PlacarPartidas + " ");
                reseta();
            }

        } else if (aux.contador > 8) {
            JOptionPane.showMessageDialog(null, "velha!");
            placarvelha++;
            qtdVelhas.setText(placarvelha + " ");
            PlacarPartidas++;
            qtdPartidas.setText(PlacarPartidas + " ");
            reseta();

        }

    }

    public void reseta() {
        botao1.setText("") ;
        botao2.setText("");
        botao3.setText("");
        botao4.setText("");
        botao5.setText("");
        botao6.setText("");
        botao7.setText("");
        botao8.setText("");
        botao9.setText("");
        aux.contador = 0;
        labelJogadas.setText("");
        placarJogadas = 0;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SimboloO;
    private javax.swing.JLabel SimboloX;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelJogadas;
    private javax.swing.JLabel labelO;
    private javax.swing.JLabel labelPlacar;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel qtdPartidas;
    private javax.swing.JLabel qtdVelhas;
    private javax.swing.JLabel qtdpartidas;
    private javax.swing.JLabel velha;
    // End of variables declaration//GEN-END:variables
}
